name: CI

on:
  push:
    #branches: [ master, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5
      - name: Install blender
        run: sudo snap install blender --channel=3.3lts/stable --classic
      - name: Install armsdk
        run: |
          git clone --recurse-submodules https://github.com/armory3d/armsdk.git
          blender -noaudio -b -P blender/enable_addon.py
      - name: Build examples
        run: |
          git clone https://github.com/armory3d/armory_examples.git
          haxe -cp src --macro 'Project.buildGroup("armory_examples","web/examples",false,true,true,[])'
      - name: Build templates
        run: |
          git clone https://github.com/armory3d/armory_templates.git
          haxe -cp src --macro 'Project.buildGroup("armory_templates","web/templates",false,true,true,[])'
      - name: Build tutorials
        run: |
          git clone https://github.com/armory3d/armory_tutorials.git
          haxe -cp src --macro 'Project.buildGroup("armory_tutorials","web/tutorials",false,true,true,[])'
      - name: Build application
        run: |
          export ARMSDK="$(pwd)/armsdk"
          haxelib install app.hxml --always
          haxe app.hxml 


