name: CI

on:
  push:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Install blender
        run: sudo snap install blender --channel=2.93lts/stable --classic
      - name: Install armsdk
        run: |
          git clone --recurse-submodules https://github.com/armory3d/armsdk.git
          blender -noaudio -b -P blender/enable_addon.py
      - name: Build examples
        run: |
          git clone https://github.com/armory3d/armory_examples.git
          haxe build-examples.hxml 
      - name: Build templates
        run: |
          git clone https://github.com/armory3d/armory_templates.git
          haxe build-templates.hxml 
      - name: Build tutorials
        run: |
          git clone https://github.com/armory3d/armory_tutorials.git
          haxe build-tutorials.hxml 
      - name: Build application
        run: |
          export ARMSDK="$(pwd)/armsdk"
          haxelib install app.hxml --always
          haxe app.hxml 
